apiVersion: v1 
kind: Pod 
metadata:
  name: multi-container
labels:
  proejct: roboshop
  component: frontend
  createdby: vali_shaik
  environment: dev

spec:
 containers:
 - name: nginx
   image: nginx
 - name: almalinux
   image: almalinux
   command: ["sleep", "1000"]